ALTER TABLE sync_run ADD COLUMN IF NOT EXISTS files_total int NOT NULL DEFAULT 0;
ALTER TABLE sync_run ADD COLUMN IF NOT EXISTS files_done int NOT NULL DEFAULT 0;
ALTER TABLE sync_run ADD COLUMN IF NOT EXISTS chunks_total int NOT NULL DEFAULT 0;
ALTER TABLE sync_run ADD COLUMN IF NOT EXISTS chunks_done int NOT NULL DEFAULT 0;
