export {
  hybridRetrieve,
  scoreChunk,
  previewUrl,
  clipQuote,
  loadChunksViaSql,
  loadVectorChunksViaSql,
  hitKey,
  UNKNOWN_ANSWER,
  type RetrieveChunk,
  type RetrieveHit,
  type HybridRetrieveOpts,
  type HybridRetrieveResult,
  type LoadChunks,
  type LoadVectorChunks,
  type SqlQuery,
} from "./hybrid.ts";
export {
  composeExtractiveAnswer,
  composeAskAnswer,
  citationsFromHits,
  type AskCitation,
  type AskResponse,
  type ChatConfig,
} from "./answer.ts";
export {
  embedTexts,
  localProject,
  cosine,
  averageVectors,
  rrfMerge,
  formatVector,
  parseEmbedding,
  embeddingModelId,
  EMBEDDING_DIM,
  LOCAL_EMBEDDING_MODEL,
  DEFAULT_EMBEDDING_MODEL,
  type EmbedTextsOpts,
  type EmbedEndpoint,
} from "./embed.ts";

export {
  searchSourcesAndSimilar,
  similarToEmbedding,
  SIMILAR_LIMIT,
  SOURCE_RESULT_LIMIT,
  type SourceSearchHit,
  type SimilarSearchHit,
  type SearchCorpusNote,
  type SearchCorpusChunk,
  type SearchSourcesOpts,
} from "./search.ts";
